M48
; DRILL file {KiCad (6.0.0)} date Thu Jul  7 17:58:48 2022
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-07-07T17:58:48-06:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0591
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0709
%
G90
G05
T1
X4.1835Y-2.8431
X4.1835Y-3.0341
T2
X4.0642Y-2.8313
X4.0642Y-3.0459
T0
M30
